# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "cancun"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  via-ir = false
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 999
  out = "out"
  script = "scripts"
  solc = "0.8.27"
  src = "contracts"
  test = "test"
  cache_path  = "cache_forge"
  libs = ["node_modules"]
  gas_reports_ignore = ["MockToken"]
  fs_permissions = [{ access = "read", path = "script/deploy/artifacts"}, { access = "read", path = "script/deploy"}]

[profile.ci]
  fuzz = { runs = 1_000 }
  verbosity = 3

[profile.via-ir]
  via-ir = true

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[lint]
  lint_on_build = true
  ignore = [
    # Test files
    "test/*/*.t.sol",
    "test/*.t.sol", 
    "test/**/*.t.sol",
    
    # Mock contracts
    "test/mock/*.sol",
    "contracts/mock/*.sol",
    "**/mock/*.sol",
    
    # Specific file patterns that are often problematic
    "**/*Mock*.sol",
    "**/*Test*.sol",
  ]
  severity = ["high", "med", "gas"]

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = "1"}
  sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = "11155111"} 
  base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = "8453"}
  # base-sepolia
  scroll = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = "534352"} 